# Note: libasynql is placed above PoolExample so that libasynql is built before PoolExample. This ensures that the latest version of libasynql is used to infect PoolExample.
projects:
  libasynql:
    type: library
    model: virion
    path: libasynql
  PoolExample:
    path: examples/PoolExample
    libs:
      - virion project local:libasynql 1.0
