branches: master
projects:
  libasynql:
    type: library
    model: virion
    path: libasynql
  PoolExample:
    path: examples/PoolExample
    libs:
      - local-project: libasynql
  SerialExample:
    path: exapmles/SerialExample
    libs:
      - local-project: libasynql
